# Generated by Django 3.2.9 on 2022-07-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_careers'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='careers',
            name='requirements',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
